#!/usr/bin/env zsh
set -euo pipefail

status() {
  printf "%-36s %s\n" "$1" "$2"
}

display_path() {
  local path="$1"
  if [[ -n "$path" ]]; then
    print -r -- "${path//$HOME/~}"
  else
    print -r -- "missing"
  fi
}

truthy() {
  [[ "${1:-}" == "1" || "${1:-}" == "true" || "${1:-}" == "yes" ]]
}

on_macos() {
  [[ "$(uname)" == "Darwin" ]]
}

ssh_config_file() {
  local ssh_config="$HOME/.ssh/config"

  if [[ -L "$ssh_config" && -e "$ssh_config" ]]; then
    print -r -- "${ssh_config:A}"
  else
    print -r -- "$ssh_config"
  fi
}

ensure_op_plugins_file() {
  local plugin_file="$HOME/.config/op/plugins.sh"

  mkdir -p "$(dirname "$plugin_file")"
  if [[ ! -e "$plugin_file" ]]; then
    printf "export OP_PLUGIN_ALIASES_SOURCED=1\n" > "$plugin_file"
    status "op plugins.sh" "created without global aliases"
  else
    status "op plugins.sh" "present"
  fi
}

ensure_codex_mcp() {
  local mcp_bin="/Applications/1Password.app/Contents/MacOS/onepassword-mcp"

  if ! command -v codex >/dev/null 2>&1; then
    status "codex mcp:1password" "skipped; codex missing"
    return 0
  fi

  if [[ ! -x "$mcp_bin" ]]; then
    status "codex mcp:1password" "skipped; onepassword-mcp missing"
    return 0
  fi

  if codex mcp list 2>/dev/null | awk 'BEGIN{found=0} /^1password[[:space:]]/ {found=1} END{exit found ? 0 : 1}'; then
    status "codex mcp:1password" "configured"
    return 0
  fi

  if codex mcp add 1password -- "$mcp_bin"; then
    status "codex mcp:1password" "added"
  else
    status "codex mcp:1password" "failed to add"
  fi
}

ensure_ssh_config_identity_agent() {
  local ssh_dir="$HOME/.ssh"
  local ssh_config_path="$ssh_dir/config"
  local ssh_config
  local include_dir="$ssh_dir/config.d"
  local include_file="$include_dir/1password-agent.conf"
  local include_line='Include ~/.ssh/config.d/1password-agent.conf'
  local agent_path='~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock'
  local agent_socket="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  local tmp_file
  local cleaned=0
  local remove_generated_file=0
  local remove_managed_include=0

  ssh_config="$(ssh_config_file)"

  if [[ ! -S "$agent_socket" ]]; then
    if [[ -f "$include_file" ]] && grep -q '^# Generated by dotfiles scripts/setup-1password-dev\.zsh\.$' "$include_file"; then
      remove_generated_file=1
      remove_managed_include=1
    elif [[ ! -e "$include_file" ]]; then
      remove_managed_include=1
    fi

    if [[ -e "$ssh_config" && "$remove_managed_include" -eq 1 ]]; then
      tmp_file="$(mktemp)" || {
        status "ssh config include" "skipped; temp file unavailable for stale include cleanup"
        return 0
      }
      awk '
        /^[[:space:]]*Include[[:space:]]+.*\.ssh\/config\.d\/1password-agent\.conf[[:space:]]*$/ { next }
        /^# >>> dotfiles 1Password SSH agent$/ { skip=1; next }
        /^# <<< dotfiles 1Password SSH agent$/ { skip=0; next }
        skip { next }
        { print }
      ' "$ssh_config" > "$tmp_file"
      if cmp -s "$ssh_config" "$tmp_file"; then
        rm -f "$tmp_file"
      else
        mv "$tmp_file" "$ssh_config"
        chmod 600 "$ssh_config"
        cleaned=1
      fi
    fi

    if [[ "$remove_generated_file" -eq 1 ]]; then
      rm -f "$include_file"
      cleaned=1
    fi

    if [[ "$cleaned" -eq 1 ]]; then
      status "ssh config include" "removed stale config; socket missing"
    else
      status "ssh config include" "skipped; 1Password SSH agent socket missing"
    fi
    return 0
  fi

  mkdir -p "$ssh_dir" "$include_dir"
  chmod 700 "$ssh_dir"

  {
    printf "# Generated by dotfiles scripts/setup-1password-dev.zsh.\n"
    printf "# Keep this include before other Host or Match blocks in ~/.ssh/config.\n"
    printf "Host *\n"
    printf "  IdentityAgent \"%s\"\n" "$agent_path"
  } > "$include_file"
  chmod 600 "$include_file"

  if [[ ! -e "$ssh_config" ]]; then
    printf "%s\n" "$include_line" > "$ssh_config_path"
    chmod 600 "$ssh_config_path"
    status "ssh config include" "created"
    return 0
  fi

  if awk '
    /^# >>> dotfiles 1Password SSH agent$/ { marker=1 }
    /^[[:space:]]*Include[[:space:]]+~\/\.ssh\/config\.d\/1password-agent\.conf[[:space:]]*$/ { include_seen=1 }
    /^[[:space:]]*Include[[:space:]]+~\/\.ssh\/config\.d\/\*\.conf[[:space:]]*$/ && !include_seen { block_before_include=1 }
    /^[[:space:]]*(Host|Match)[[:space:]]+/ && !include_seen { block_before_include=1 }
    END { exit (include_seen && !marker && !block_before_include) ? 0 : 1 }
  ' "$ssh_config"; then
    status "ssh config include" "present before SSH blocks"
    return 0
  fi

  tmp_file="$(mktemp)" || {
    status "ssh config include" "skipped; mktemp failed"
    return 0
  }
  awk -v include_line="$include_line" '
    function emit_include() {
      if (!emitted) {
        print include_line
        print ""
        emitted = 1
      }
    }
    /^[[:space:]]*Include[[:space:]]+.*\.ssh\/config\.d\/1password-agent\.conf[[:space:]]*$/ { next }
    /^# >>> dotfiles 1Password SSH agent$/ { skip=1; next }
    /^# <<< dotfiles 1Password SSH agent$/ { skip=0; next }
    skip { next }
    /^[[:space:]]*Include[[:space:]]+~\/\.ssh\/config\.d\/\*\.conf[[:space:]]*$/ { emit_include() }
    /^[[:space:]]*(Host|Match)[[:space:]]+/ { emit_include() }
    { print }
    END { emit_include() }
  ' "$ssh_config" > "$tmp_file"
  if cmp -s "$ssh_config" "$tmp_file"; then
    rm -f "$tmp_file"
    status "ssh config include" "present before SSH blocks"
  else
    mv "$tmp_file" "$ssh_config"
    status "ssh config include" "ensured before SSH blocks"
  fi

  chmod 600 "$ssh_config"
}

ssh_agent_has_keys() {
  local agent_socket="$1"
  local key_count

  [[ -n "$agent_socket" && -S "$agent_socket" ]] || return 1
  SSH_AUTH_SOCK="$agent_socket" ssh-add -l >/dev/null 2>&1 || return 1
  key_count="$(SSH_AUTH_SOCK="$agent_socket" ssh-add -l 2>/dev/null | wc -l | tr -d ' ')"
  [[ "${key_count:-0}" -gt 0 ]]
}

github_ssh_auth_ready() {
  local configured_agent=""
  local ssh_config

  ssh_config="$(ssh_config_file)"

  if command -v ssh >/dev/null 2>&1 && [[ -f "$ssh_config" ]]; then
    configured_agent="$(ssh -F "$ssh_config" -G github.com 2>/dev/null | awk 'tolower($1) == "identityagent" { $1=""; sub(/^[[:space:]]+/, ""); print; exit }' || true)"
  fi

  case "$configured_agent" in
    "")
      ssh_agent_has_keys "${SSH_AUTH_SOCK:-}"
      ;;
    "none")
      return 1
      ;;
    "SSH_AUTH_SOCK")
      ssh_agent_has_keys "${SSH_AUTH_SOCK:-}"
      ;;
    "~/"*)
      ssh_agent_has_keys "$HOME/${configured_agent#"~/"}"
      ;;
    *)
      ssh_agent_has_keys "$configured_agent"
      ;;
  esac
}

github_ssh_login_ready() {
  local ssh_config
  local output
  local rc

  ssh_config="$(ssh_config_file)"
  [[ -f "$ssh_config" ]] || return 1

  set +e
  output="$(ssh -F "$ssh_config" -o BatchMode=yes -o NumberOfPasswordPrompts=0 -o ConnectTimeout=5 -T git@github.com 2>&1)"
  rc=$?
  set -e

  [[ "$rc" -eq 1 && "$output" == *"successfully authenticated"* ]]
}

ensure_gh_ssh_protocol() {
  if ! command -v gh >/dev/null 2>&1; then
    status "gh git_protocol" "skipped; gh missing"
    return 0
  fi

  if ! github_ssh_auth_ready || ! github_ssh_login_ready; then
    status "gh git_protocol" "skipped; SSH auth unavailable"
    return 0
  fi

  if [[ "$(gh config get git_protocol -h github.com 2>/dev/null || true)" == "ssh" ]]; then
    status "gh git_protocol" "ssh"
    return 0
  fi

  if gh config set git_protocol ssh -h github.com >/dev/null 2>&1; then
    status "gh git_protocol" "set to ssh"
  else
    status "gh git_protocol" "failed to set"
  fi
}

write_agent_toml_from_1password() {
  local agent_config="$HOME/.config/1Password/ssh/agent.toml"
  local host_alias="${AGENT_HOST_ALIAS:-$(hostname -s)}"
  local peer_priority="${ONEPASSWORD_SSH_KEY_PRIORITY:-kakarot vegeta cabba piccolo gohan broly}"
  local tmp_file
  local item_count
  local should_refresh=0

  if truthy "${ONEPASSWORD_REFRESH_SSH_KEYS:-0}"; then
    should_refresh=1
  elif [[ ! -e "$agent_config" && -t 0 && -t 1 ]]; then
    should_refresh=1
  fi

  if [[ "$should_refresh" -ne 1 ]]; then
    if [[ -e "$agent_config" ]]; then
      status "agent.toml" "present; not refreshed"
    else
      status "agent.toml" "missing; rerun with ONEPASSWORD_REFRESH_SSH_KEYS=1"
    fi
    return 0
  fi

  if ! command -v op >/dev/null 2>&1; then
    status "agent.toml" "skipped; op missing"
    return 0
  fi

  if ! command -v jq >/dev/null 2>&1; then
    status "agent.toml" "skipped; jq missing"
    return 0
  fi

  tmp_file="$(mktemp)" || {
    status "agent.toml" "skipped; mktemp failed"
    return 0
  }
  if ! op item list --categories "SSH Key" --format json 2>/dev/null \
    | jq -r --arg host "$host_alias" --arg priority "$peer_priority" '
      def words($value):
        $value | ascii_downcase | gsub("[^a-z0-9]+"; " ") | split(" ") | map(select(length > 0));
      def has_word($words; $word):
        ($words | index($word | ascii_downcase)) != null;
      def priority_index($title):
        ($priority | split(" ")) as $names
        | words($title) as $words
        | reduce range(0; $names | length) as $i
            (999; if has_word($words; $names[$i]) then [$i, .] | min else . end);
      def score:
        (.title | ascii_downcase) as $title
        | ($host | ascii_downcase | sub("\\.local$"; "")) as $host_base
        | words(.title) as $words
        | if $title == ($host_base + ".local ssh key") then 0
          elif $title == ($host_base + " ssh key") then 0
          elif has_word($words; $host_base) then 1
          else 10 + priority_index($title)
          end;
      sort_by(score, (.title | ascii_downcase))
      | .[:6]
      | "# Generated by dotfiles scripts/setup-1password-dev.zsh.\n"
        + "# This file contains 1Password item and vault IDs only, not private keys.\n"
        + "# Keep the list short to avoid SSH servers common six-key auth limit.\n\n"
        + (map("[[ssh-keys]]\nitem = " + (.id | @json) + "\nvault = " + (.vault.id | @json) + "\n") | join("\n"))
    ' > "$tmp_file"; then
    rm -f "$tmp_file"
    status "agent.toml" "skipped; op item list unavailable"
    return 0
  fi

  item_count="$(grep -c '^\[\[ssh-keys\]\]' "$tmp_file" || true)"
  if [[ "$item_count" -eq 0 ]]; then
    rm -f "$tmp_file"
    status "agent.toml" "skipped; no SSH Key items found"
    return 0
  fi

  mkdir -p "$(dirname "$agent_config")"
  mv "$tmp_file" "$agent_config"
  chmod 600 "$agent_config"
  status "agent.toml" "wrote $item_count entries"
}

main() {
  if ! on_macos; then
    status "1Password dev setup" "skipped; not macOS"
    return 0
  fi

  status "1Password.app" "$([[ -d /Applications/1Password.app ]] && printf present || printf missing)"
  status "op" "$(display_path "$(command -v op 2>/dev/null || true)")"
  status "onepassword-mcp" "$([[ -x /Applications/1Password.app/Contents/MacOS/onepassword-mcp ]] && printf present || printf missing)"

  ensure_op_plugins_file
  ensure_codex_mcp
  ensure_ssh_config_identity_agent
  write_agent_toml_from_1password
  ensure_gh_ssh_protocol
}

main "$@"
